import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: 1,
    title: "List all customers",
    topic: "Basic SELECT",
    difficulty: "Easy",
    description: "Return all rows and columns from the customers table.",
    starterSql: "-- Select every column from customers.\nSELECT\n  *\nFROM customers;",
    solutionSql: "SELECT *\nFROM customers;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 2,
    title: "Customer names and email addresses",
    topic: "Basic SELECT",
    difficulty: "Easy",
    description: "Return first_name, last_name, and email for every customer.",
    starterSql: "-- Choose only the requested columns.\nSELECT\n  first_name,\n  -- add the other columns\nFROM customers;",
    solutionSql: "SELECT first_name, last_name, email\nFROM customers;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 3,
    title: "Product price list",
    topic: "Basic SELECT",
    difficulty: "Easy",
    description: "Return product_id, product_name, category, and unit_price for every product.",
    starterSql: "-- Build a compact product catalog query.\nSELECT\n  product_id,\n  product_name\nFROM products;",
    solutionSql: "SELECT product_id, product_name, category, unit_price\nFROM products;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 4,
    title: "Unique customer countries",
    topic: "DISTINCT",
    difficulty: "Easy",
    description: "Return each country that appears in the customers table once.",
    starterSql: "-- Use DISTINCT to remove duplicates.\nSELECT DISTINCT\n  country\nFROM customers;",
    solutionSql: "SELECT DISTINCT country\nFROM customers;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 5,
    title: "Unique product categories",
    topic: "DISTINCT",
    difficulty: "Easy",
    description: "Return each product category once.",
    starterSql: "-- Return one row per category.\nSELECT DISTINCT\n  -- category column\nFROM products;",
    solutionSql: "SELECT DISTINCT category\nFROM products;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 6,
    title: "Unique order payment methods",
    topic: "DISTINCT",
    difficulty: "Easy",
    description: "Return each payment method used in orders once.",
    starterSql: "-- Look at the payment_method column in orders.\nSELECT DISTINCT\n  payment_method\nFROM orders;",
    solutionSql: "SELECT DISTINCT payment_method\nFROM orders;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 7,
    title: "Customers in Germany",
    topic: "WHERE",
    difficulty: "Easy",
    description: "Return customer_id, first_name, last_name, and city for customers whose country is Germany.",
    starterSql: "-- Filter rows with WHERE.\nSELECT customer_id, first_name, last_name, city\nFROM customers\nWHERE country = '...';",
    solutionSql: "SELECT customer_id, first_name, last_name, city\nFROM customers\nWHERE country = 'Germany';",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 8,
    title: "Active products in stock",
    topic: "WHERE",
    difficulty: "Easy",
    description: "Return product_id, product_name, and stock_quantity for active products that have stock available.",
    starterSql: "-- Combine boolean and numeric filters.\nSELECT product_id, product_name, stock_quantity\nFROM products\nWHERE is_active = true;",
    solutionSql: "SELECT product_id, product_name, stock_quantity\nFROM products\nWHERE is_active = true\n  AND stock_quantity > 0;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 9,
    title: "Completed orders only",
    topic: "WHERE",
    difficulty: "Easy",
    description: "Return order_id, customer_id, product_id, and order_date for orders with status Completed.",
    starterSql: "-- Filter orders by status.\nSELECT order_id, customer_id, product_id, order_date\nFROM orders\nWHERE status = '...';",
    solutionSql: "SELECT order_id, customer_id, product_id, order_date\nFROM orders\nWHERE status = 'Completed';",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 10,
    title: "Turkish consumer customers",
    topic: "AND / OR",
    difficulty: "Easy",
    description: "Return customer_id, first_name, last_name, country, and segment for customers in Turkey whose segment is Consumer.",
    starterSql: "-- Both conditions must be true.\nSELECT customer_id, first_name, last_name, country, segment\nFROM customers\nWHERE country = 'Turkey';",
    solutionSql: "SELECT customer_id, first_name, last_name, country, segment\nFROM customers\nWHERE country = 'Turkey'\n  AND segment = 'Consumer';",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 11,
    title: "Cancelled or returned orders",
    topic: "AND / OR",
    difficulty: "Easy",
    description: "Return order_id, status, and payment_method for orders that are Cancelled or Returned.",
    starterSql: "-- Use OR to match either status.\nSELECT order_id, status, payment_method\nFROM orders\nWHERE status = 'Cancelled';",
    solutionSql: "SELECT order_id, status, payment_method\nFROM orders\nWHERE status = 'Cancelled'\n   OR status = 'Returned';",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 12,
    title: "Expensive electronics or home products",
    topic: "AND / OR",
    difficulty: "Medium",
    description: "Return product_id, product_name, category, and unit_price for active Electronics or Home products priced above 40.",
    starterSql: "-- Use parentheses around OR categories.\nSELECT product_id, product_name, category, unit_price\nFROM products\nWHERE is_active = true\n  AND (...);",
    solutionSql: "SELECT product_id, product_name, category, unit_price\nFROM products\nWHERE is_active = true\n  AND unit_price > 40\n  AND (category = 'Electronics' OR category = 'Home');",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 13,
    title: "Customers in selected countries",
    topic: "IN",
    difficulty: "Easy",
    description: "Return customer_id, first_name, last_name, and country for customers in Turkey, Germany, or France.",
    starterSql: "-- IN is shorter than several OR conditions.\nSELECT customer_id, first_name, last_name, country\nFROM customers\nWHERE country IN (...);",
    solutionSql: "SELECT customer_id, first_name, last_name, country\nFROM customers\nWHERE country IN ('Turkey', 'Germany', 'France');",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 14,
    title: "Orders paid by card or PayPal",
    topic: "IN",
    difficulty: "Easy",
    description: "Return order_id, payment_method, and status for orders paid by Card or PayPal.",
    starterSql: "-- Match multiple payment methods.\nSELECT order_id, payment_method, status\nFROM orders\nWHERE payment_method IN (...);",
    solutionSql: "SELECT order_id, payment_method, status\nFROM orders\nWHERE payment_method IN ('Card', 'PayPal');",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 15,
    title: "Books and accessories",
    topic: "IN",
    difficulty: "Easy",
    description: "Return product_id, product_name, and category for products in the Books or Accessories categories.",
    starterSql: "-- Filter categories with IN.\nSELECT product_id, product_name, category\nFROM products\nWHERE category IN (...);",
    solutionSql: "SELECT product_id, product_name, category\nFROM products\nWHERE category IN ('Books', 'Accessories');",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 16,
    title: "Products priced between 20 and 60",
    topic: "BETWEEN",
    difficulty: "Easy",
    description: "Return product_id, product_name, and unit_price for products priced from 20 through 60 inclusive.",
    starterSql: "-- BETWEEN includes both endpoints.\nSELECT product_id, product_name, unit_price\nFROM products\nWHERE unit_price BETWEEN ... AND ...;",
    solutionSql: "SELECT product_id, product_name, unit_price\nFROM products\nWHERE unit_price BETWEEN 20 AND 60;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 17,
    title: "Orders in the first quarter of 2024",
    topic: "BETWEEN",
    difficulty: "Easy",
    description: "Return order_id, order_date, and status for orders from 2024-01-01 through 2024-03-31.",
    starterSql: "-- Dates can be compared with BETWEEN.\nSELECT order_id, order_date, status\nFROM orders\nWHERE order_date BETWEEN DATE '...' AND DATE '...';",
    solutionSql: "SELECT order_id, order_date, status\nFROM orders\nWHERE order_date BETWEEN DATE '2024-01-01' AND DATE '2024-03-31';",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 18,
    title: "Medium-sized order quantities",
    topic: "BETWEEN",
    difficulty: "Easy",
    description: "Return order_id and quantity for orders with quantity between 2 and 4 inclusive.",
    starterSql: "-- Filter quantity with BETWEEN.\nSELECT order_id, quantity\nFROM orders\nWHERE quantity BETWEEN ... AND ...;",
    solutionSql: "SELECT order_id, quantity\nFROM orders\nWHERE quantity BETWEEN 2 AND 4;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 19,
    title: "Newest signups first",
    topic: "ORDER BY",
    difficulty: "Easy",
    description: "Return customer_id, first_name, last_name, and signup_date for all customers, ordered by signup_date from newest to oldest.",
    starterSql: "-- This question requires row order.\nSELECT customer_id, first_name, last_name, signup_date\nFROM customers\nORDER BY ...;",
    solutionSql: "SELECT customer_id, first_name, last_name, signup_date\nFROM customers\nORDER BY signup_date DESC;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 20,
    title: "Cheapest products first",
    topic: "ORDER BY",
    difficulty: "Easy",
    description: "Return product_id, product_name, and unit_price ordered from cheapest to most expensive.",
    starterSql: "-- Sort by unit_price ascending.\nSELECT product_id, product_name, unit_price\nFROM products\nORDER BY ...;",
    solutionSql: "SELECT product_id, product_name, unit_price\nFROM products\nORDER BY unit_price ASC;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 21,
    title: "Orders by status then date",
    topic: "ORDER BY",
    difficulty: "Easy",
    description: "Return order_id, status, and order_date ordered by status alphabetically, then order_date newest first.",
    starterSql: "-- Use more than one sort expression.\nSELECT order_id, status, order_date\nFROM orders\nORDER BY status, ...;",
    solutionSql: "SELECT order_id, status, order_date\nFROM orders\nORDER BY status ASC, order_date DESC;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 22,
    title: "Five most expensive products",
    topic: "LIMIT",
    difficulty: "Easy",
    description: "Return product_id, product_name, and unit_price for the five most expensive products.",
    starterSql: "-- Sort first, then limit the result.\nSELECT product_id, product_name, unit_price\nFROM products\nORDER BY unit_price DESC\nLIMIT ...;",
    solutionSql: "SELECT product_id, product_name, unit_price\nFROM products\nORDER BY unit_price DESC\nLIMIT 5;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 23,
    title: "Ten newest orders",
    topic: "LIMIT",
    difficulty: "Easy",
    description: "Return order_id, order_date, status, and quantity for the ten newest orders.",
    starterSql: "-- Use ORDER BY with LIMIT.\nSELECT order_id, order_date, status, quantity\nFROM orders\nORDER BY ...\nLIMIT ...;",
    solutionSql: "SELECT order_id, order_date, status, quantity\nFROM orders\nORDER BY order_date DESC, order_id DESC\nLIMIT 10;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 24,
    title: "First three customers alphabetically",
    topic: "LIMIT",
    difficulty: "Easy",
    description: "Return customer_id, first_name, and last_name for the first three customers ordered by last_name then first_name.",
    starterSql: "-- Sort names before limiting.\nSELECT customer_id, first_name, last_name\nFROM customers\nORDER BY ...\nLIMIT 3;",
    solutionSql: "SELECT customer_id, first_name, last_name\nFROM customers\nORDER BY last_name ASC, first_name ASC\nLIMIT 3;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 25,
    title: "Orders with customer and product names",
    topic: "JOIN",
    difficulty: "Easy",
    description: "Return order_id, customer full_name, product_name, and quantity for every order, ordered by order_id.",
    starterSql: "-- Join orders to customers and products.\nSELECT\n  o.order_id,\n  -- build full_name,\n  -- product name,\n  o.quantity\nFROM orders o\nJOIN customers c ON ...\nJOIN products p ON ...\nORDER BY o.order_id;",
    solutionSql: "SELECT\n  o.order_id,\n  c.first_name || ' ' || c.last_name AS full_name,\n  p.product_name,\n  o.quantity\nFROM orders o\nJOIN customers c ON c.customer_id = o.customer_id\nJOIN products p ON p.product_id = o.product_id\nORDER BY o.order_id;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 26,
    title: "Completed card order details",
    topic: "JOIN",
    difficulty: "Easy",
    description: "Return order_id, customer email, product_name, and payment_method for completed orders paid by Card.",
    starterSql: "-- Join three tables, then filter.\nSELECT o.order_id, c.email, p.product_name, o.payment_method\nFROM orders o\nJOIN customers c ON ...\nJOIN products p ON ...\nWHERE ...;",
    solutionSql: "SELECT o.order_id, c.email, p.product_name, o.payment_method\nFROM orders o\nJOIN customers c ON c.customer_id = o.customer_id\nJOIN products p ON p.product_id = o.product_id\nWHERE o.status = 'Completed'\n  AND o.payment_method = 'Card';",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 27,
    title: "Completed order line totals",
    topic: "JOIN",
    difficulty: "Medium",
    description: "Return order_id, product_name, quantity, unit_price, and line_total for completed orders. line_total is quantity times unit_price after discount.",
    starterSql: "-- Join products to calculate money values.\nSELECT\n  o.order_id,\n  p.product_name,\n  o.quantity,\n  p.unit_price,\n  -- calculate line_total\nFROM orders o\nJOIN products p ON ...\nWHERE o.status = 'Completed';",
    solutionSql: "SELECT\n  o.order_id,\n  p.product_name,\n  o.quantity,\n  p.unit_price,\n  ROUND(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0), 2) AS line_total\nFROM orders o\nJOIN products p ON p.product_id = o.product_id\nWHERE o.status = 'Completed';",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 28,
    title: "Customers without completed orders",
    topic: "LEFT JOIN",
    difficulty: "Medium",
    description: "Return customer_id, first_name, and last_name for customers who do not have any completed orders.",
    starterSql: "-- LEFT JOIN and keep rows where the joined order is missing.\nSELECT c.customer_id, c.first_name, c.last_name\nFROM customers c\nLEFT JOIN orders o ON ...\nWHERE o.order_id IS NULL;",
    solutionSql: "SELECT c.customer_id, c.first_name, c.last_name\nFROM customers c\nLEFT JOIN orders o\n  ON o.customer_id = c.customer_id\n  AND o.status = 'Completed'\nWHERE o.order_id IS NULL;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 29,
    title: "Products never ordered",
    topic: "LEFT JOIN",
    difficulty: "Medium",
    description: "Return product_id and product_name for products that do not appear in any order.",
    starterSql: "-- LEFT JOIN products to orders and look for NULL order rows.\nSELECT p.product_id, p.product_name\nFROM products p\nLEFT JOIN orders o ON ...\nWHERE ...;",
    solutionSql: "SELECT p.product_id, p.product_name\nFROM products p\nLEFT JOIN orders o ON o.product_id = p.product_id\nWHERE o.order_id IS NULL;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 30,
    title: "All customers with completed order counts",
    topic: "LEFT JOIN",
    difficulty: "Medium",
    description: "Return every customer with completed_order_count. Customers with zero completed orders should still appear.",
    starterSql: "-- Count only completed joined orders.\nSELECT\n  c.customer_id,\n  c.first_name,\n  c.last_name,\n  COUNT(...) AS completed_order_count\nFROM customers c\nLEFT JOIN orders o ON ...\nGROUP BY c.customer_id, c.first_name, c.last_name;",
    solutionSql: "SELECT\n  c.customer_id,\n  c.first_name,\n  c.last_name,\n  COUNT(o.order_id) AS completed_order_count\nFROM customers c\nLEFT JOIN orders o\n  ON o.customer_id = c.customer_id\n  AND o.status = 'Completed'\nGROUP BY c.customer_id, c.first_name, c.last_name;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 31,
    title: "Orders by status",
    topic: "GROUP BY",
    difficulty: "Easy",
    description: "Return each order status and the number of orders with that status. Name the count column order_count.",
    starterSql: "-- Aggregate rows per status.\nSELECT status, COUNT(*) AS order_count\nFROM orders\nGROUP BY ...;",
    solutionSql: "SELECT status, COUNT(*) AS order_count\nFROM orders\nGROUP BY status;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 32,
    title: "Customers by country",
    topic: "GROUP BY",
    difficulty: "Easy",
    description: "Return country and customer_count for each country.",
    starterSql: "-- Count customers per country.\nSELECT country, COUNT(*) AS customer_count\nFROM customers\nGROUP BY ...;",
    solutionSql: "SELECT country, COUNT(*) AS customer_count\nFROM customers\nGROUP BY country;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 33,
    title: "Revenue by category",
    topic: "GROUP BY",
    difficulty: "Medium",
    description: "Return each product category and total revenue after discounts for completed orders. Name the revenue column total_revenue.",
    starterSql: "-- Join orders to products and SUM discounted line totals.\nSELECT\n  p.category,\n  -- total revenue\nFROM orders o\nJOIN products p ON ...\nWHERE o.status = 'Completed'\nGROUP BY p.category;",
    solutionSql: "SELECT\n  p.category,\n  ROUND(SUM(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0)), 2) AS total_revenue\nFROM orders o\nJOIN products p ON p.product_id = o.product_id\nWHERE o.status = 'Completed'\nGROUP BY p.category;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 34,
    title: "Customers with many orders",
    topic: "HAVING",
    difficulty: "Medium",
    description: "Return customer_id and order_count for customers who have placed more than 3 orders.",
    starterSql: "-- HAVING filters grouped rows.\nSELECT customer_id, COUNT(*) AS order_count\nFROM orders\nGROUP BY customer_id\nHAVING ...;",
    solutionSql: "SELECT customer_id, COUNT(*) AS order_count\nFROM orders\nGROUP BY customer_id\nHAVING COUNT(*) > 3;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 35,
    title: "Products selling more than 20 units",
    topic: "HAVING",
    difficulty: "Medium",
    description: "Return product_id, product_name, and units_sold for products with more than 20 total units ordered.",
    starterSql: "-- SUM quantity per product, then filter the grouped result.\nSELECT p.product_id, p.product_name, SUM(o.quantity) AS units_sold\nFROM products p\nJOIN orders o ON ...\nGROUP BY p.product_id, p.product_name\nHAVING ...;",
    solutionSql: "SELECT p.product_id, p.product_name, SUM(o.quantity) AS units_sold\nFROM products p\nJOIN orders o ON o.product_id = p.product_id\nGROUP BY p.product_id, p.product_name\nHAVING SUM(o.quantity) > 20;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 36,
    title: "Countries with at least three customers",
    topic: "HAVING",
    difficulty: "Medium",
    description: "Return country and customer_count for countries that have at least 3 customers.",
    starterSql: "-- Use HAVING after GROUP BY.\nSELECT country, COUNT(*) AS customer_count\nFROM customers\nGROUP BY country\nHAVING COUNT(*) >= ...;",
    solutionSql: "SELECT country, COUNT(*) AS customer_count\nFROM customers\nGROUP BY country\nHAVING COUNT(*) >= 3;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 37,
    title: "Order aggregate summary",
    topic: "aggregate functions",
    difficulty: "Easy",
    description: "Return order_count, total_quantity, average_quantity, min_quantity, and max_quantity for all orders.",
    starterSql: "-- Use COUNT, SUM, AVG, MIN, and MAX.\nSELECT\n  COUNT(*) AS order_count\nFROM orders;",
    solutionSql: "SELECT\n  COUNT(*) AS order_count,\n  SUM(quantity) AS total_quantity,\n  ROUND(AVG(quantity), 2) AS average_quantity,\n  MIN(quantity) AS min_quantity,\n  MAX(quantity) AS max_quantity\nFROM orders;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 38,
    title: "Average price by category",
    topic: "aggregate functions",
    difficulty: "Easy",
    description: "Return category and average_unit_price rounded to 2 decimal places for each product category.",
    starterSql: "-- AVG can be grouped by category.\nSELECT category, ROUND(AVG(unit_price), 2) AS average_unit_price\nFROM products\nGROUP BY ...;",
    solutionSql: "SELECT category, ROUND(AVG(unit_price), 2) AS average_unit_price\nFROM products\nGROUP BY category;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 39,
    title: "Completed revenue summary",
    topic: "aggregate functions",
    difficulty: "Medium",
    description: "Return completed_order_count and completed_revenue for all completed orders.",
    starterSql: "-- Join orders and products, then aggregate completed rows.\nSELECT\n  COUNT(*) AS completed_order_count,\n  -- SUM discounted revenue\nFROM orders o\nJOIN products p ON ...\nWHERE o.status = 'Completed';",
    solutionSql: "SELECT\n  COUNT(*) AS completed_order_count,\n  ROUND(SUM(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0)), 2) AS completed_revenue\nFROM orders o\nJOIN products p ON p.product_id = o.product_id\nWHERE o.status = 'Completed';",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 40,
    title: "Orders from 2024",
    topic: "date functions",
    difficulty: "Easy",
    description: "Return order_id, order_date, and status for orders placed during calendar year 2024.",
    starterSql: "-- Use a half-open date range.\nSELECT order_id, order_date, status\nFROM orders\nWHERE order_date >= DATE '2024-01-01';",
    solutionSql: "SELECT order_id, order_date, status\nFROM orders\nWHERE order_date >= DATE '2024-01-01'\n  AND order_date < DATE '2025-01-01';",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 41,
    title: "Monthly order counts",
    topic: "date functions",
    difficulty: "Medium",
    description: "Return order_month and order_count for each month. Use DATE_TRUNC('month', order_date)::date as order_month and order by month.",
    starterSql: "-- DATE_TRUNC groups dates into months.\nSELECT DATE_TRUNC('month', order_date)::date AS order_month, COUNT(*) AS order_count\nFROM orders\nGROUP BY order_month\nORDER BY ...;",
    solutionSql: "SELECT DATE_TRUNC('month', order_date)::date AS order_month, COUNT(*) AS order_count\nFROM orders\nGROUP BY order_month\nORDER BY order_month;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 42,
    title: "Customer signup age in days",
    topic: "date functions",
    difficulty: "Medium",
    description: "Return customer_id, signup_date, and days_since_signup calculated as DATE '2025-02-01' minus signup_date.",
    starterSql: "-- Subtracting dates returns days in PostgreSQL.\nSELECT customer_id, signup_date, DATE '2025-02-01' - signup_date AS days_since_signup\nFROM customers;",
    solutionSql: "SELECT customer_id, signup_date, DATE '2025-02-01' - signup_date AS days_since_signup\nFROM customers;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 43,
    title: "Order size labels",
    topic: "CASE WHEN",
    difficulty: "Easy",
    description: "Return order_id, quantity, and size_label. Use Small for quantity 1, Medium for 2 or 3, and Large for 4 or more.",
    starterSql: "-- CASE returns labels from conditions.\nSELECT\n  order_id,\n  quantity,\n  CASE\n    WHEN quantity = 1 THEN 'Small'\n    -- add more branches\n  END AS size_label\nFROM orders;",
    solutionSql: "SELECT\n  order_id,\n  quantity,\n  CASE\n    WHEN quantity = 1 THEN 'Small'\n    WHEN quantity IN (2, 3) THEN 'Medium'\n    ELSE 'Large'\n  END AS size_label\nFROM orders;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 44,
    title: "Domestic vs international customers",
    topic: "CASE WHEN",
    difficulty: "Easy",
    description: "Return customer_id, country, and market. Customers in Turkey should be Domestic; all others should be International.",
    starterSql: "-- Use CASE for a two-way label.\nSELECT\n  customer_id,\n  country,\n  CASE WHEN ... THEN ... ELSE ... END AS market\nFROM customers;",
    solutionSql: "SELECT\n  customer_id,\n  country,\n  CASE WHEN country = 'Turkey' THEN 'Domestic' ELSE 'International' END AS market\nFROM customers;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 45,
    title: "Product price bands",
    topic: "CASE WHEN",
    difficulty: "Medium",
    description: "Return product_id, product_name, unit_price, and price_band. Use Budget for prices under 25, Standard for prices under 75, and Premium otherwise.",
    starterSql: "-- CASE branches are evaluated in order.\nSELECT\n  product_id,\n  product_name,\n  unit_price,\n  CASE\n    WHEN unit_price < 25 THEN 'Budget'\n    -- add remaining bands\n  END AS price_band\nFROM products;",
    solutionSql: "SELECT\n  product_id,\n  product_name,\n  unit_price,\n  CASE\n    WHEN unit_price < 25 THEN 'Budget'\n    WHEN unit_price < 75 THEN 'Standard'\n    ELSE 'Premium'\n  END AS price_band\nFROM products;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 46,
    title: "Top customers by revenue",
    topic: "CTE",
    difficulty: "Medium",
    description: "Use a CTE to calculate completed-order revenue by customer. Return the top 5 customers by revenue with full_name and total_revenue.",
    starterSql: "WITH customer_revenue AS (\n  -- calculate revenue per customer here\n)\nSELECT full_name, total_revenue\nFROM customer_revenue\nORDER BY total_revenue DESC\nLIMIT 5;",
    solutionSql: "WITH customer_revenue AS (\n  SELECT\n    c.customer_id,\n    c.first_name || ' ' || c.last_name AS full_name,\n    ROUND(SUM(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0)), 2) AS total_revenue\n  FROM orders o\n  JOIN customers c ON c.customer_id = o.customer_id\n  JOIN products p ON p.product_id = o.product_id\n  WHERE o.status = 'Completed'\n  GROUP BY c.customer_id, full_name\n)\nSELECT full_name, total_revenue\nFROM customer_revenue\nORDER BY total_revenue DESC\nLIMIT 5;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 47,
    title: "First order per customer",
    topic: "CTE",
    difficulty: "Medium",
    description: "Use a CTE to return each customer_id with their first_order_date.",
    starterSql: "WITH first_orders AS (\n  -- one row per customer with MIN(order_date)\n)\nSELECT customer_id, first_order_date\nFROM first_orders;",
    solutionSql: "WITH first_orders AS (\n  SELECT customer_id, MIN(order_date) AS first_order_date\n  FROM orders\n  GROUP BY customer_id\n)\nSELECT customer_id, first_order_date\nFROM first_orders;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 48,
    title: "Category revenue percentages",
    topic: "CTE",
    difficulty: "Medium",
    description: "Use CTEs to return category, total_revenue, and revenue_share_percent for completed order revenue by category.",
    starterSql: "WITH category_revenue AS (\n  -- revenue per category\n), total_revenue AS (\n  -- grand total\n)\nSELECT ...;",
    solutionSql: "WITH category_revenue AS (\n  SELECT\n    p.category,\n    SUM(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0)) AS total_revenue\n  FROM orders o\n  JOIN products p ON p.product_id = o.product_id\n  WHERE o.status = 'Completed'\n  GROUP BY p.category\n), total_revenue AS (\n  SELECT SUM(total_revenue) AS grand_total\n  FROM category_revenue\n)\nSELECT\n  cr.category,\n  ROUND(cr.total_revenue, 2) AS total_revenue,\n  ROUND(cr.total_revenue / tr.grand_total * 100, 2) AS revenue_share_percent\nFROM category_revenue cr\nCROSS JOIN total_revenue tr;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 49,
    title: "Query the order line view",
    topic: "VIEW",
    difficulty: "Medium",
    description: "Query the order_line_items view. Return order_id, product_name, total_after_discount, and status for the first 10 completed rows by order_id.",
    starterSql: "-- The view already joins orders, customers, and products.\nSELECT order_id, product_name, total_after_discount, status\nFROM order_line_items\nWHERE ...\nORDER BY ...\nLIMIT 10;",
    solutionSql: "SELECT order_id, product_name, total_after_discount, status\nFROM order_line_items\nWHERE status = 'Completed'\nORDER BY order_id\nLIMIT 10;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 50,
    title: "Create a completed order summary view",
    topic: "VIEW",
    difficulty: "Medium",
    description: "Create a view named completed_order_summary with order_id, customer_name, product_name, order_date, and total_after_discount for completed orders.",
    starterSql: "-- Manual exercise: create the requested view.\nCREATE VIEW completed_order_summary AS\nSELECT\n  -- requested columns\nFROM orders o\nJOIN customers c ON ...\nJOIN products p ON ...\nWHERE ...;",
    solutionSql: "CREATE VIEW completed_order_summary AS\nSELECT\n  o.order_id,\n  c.first_name || ' ' || c.last_name AS customer_name,\n  p.product_name,\n  o.order_date,\n  ROUND(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0), 2) AS total_after_discount\nFROM orders o\nJOIN customers c ON c.customer_id = o.customer_id\nJOIN products p ON p.product_id = o.product_id\nWHERE o.status = 'Completed';",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 51,
    title: "Products above average price",
    topic: "SUBQUERY",
    difficulty: "Medium",
    description: "Return product_id, product_name, and unit_price for products priced above the average product price.",
    starterSql: "-- Put AVG(unit_price) in a scalar subquery.\nSELECT product_id, product_name, unit_price\nFROM products\nWHERE unit_price > (...);",
    solutionSql: "SELECT product_id, product_name, unit_price\nFROM products\nWHERE unit_price > (SELECT AVG(unit_price) FROM products);",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 52,
    title: "Customers who bought electronics",
    topic: "SUBQUERY",
    difficulty: "Medium",
    description: "Return customer_id, first_name, and last_name for customers who have ordered at least one Electronics product.",
    starterSql: "-- Use IN with a subquery that finds matching customer_id values.\nSELECT customer_id, first_name, last_name\nFROM customers\nWHERE customer_id IN (...);",
    solutionSql: "SELECT customer_id, first_name, last_name\nFROM customers\nWHERE customer_id IN (\n  SELECT o.customer_id\n  FROM orders o\n  JOIN products p ON p.product_id = o.product_id\n  WHERE p.category = 'Electronics'\n);",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 53,
    title: "Orders larger than the average quantity",
    topic: "SUBQUERY",
    difficulty: "Medium",
    description: "Return order_id, quantity, and status for orders whose quantity is greater than the average order quantity.",
    starterSql: "-- Compare quantity to a subquery.\nSELECT order_id, quantity, status\nFROM orders\nWHERE quantity > (...);",
    solutionSql: "SELECT order_id, quantity, status\nFROM orders\nWHERE quantity > (SELECT AVG(quantity) FROM orders);",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 54,
    title: "Revenue rank by customer",
    topic: "WINDOW FUNCTIONS",
    difficulty: "Medium",
    description: "Return full_name, total_revenue, and revenue_rank for completed-order revenue by customer. Rank highest revenue as 1.",
    starterSql: "WITH customer_revenue AS (\n  -- calculate completed revenue per customer\n)\nSELECT\n  full_name,\n  total_revenue,\n  -- rank by total_revenue descending\nFROM customer_revenue;",
    solutionSql: "WITH customer_revenue AS (\n  SELECT\n    c.customer_id,\n    c.first_name || ' ' || c.last_name AS full_name,\n    ROUND(SUM(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0)), 2) AS total_revenue\n  FROM orders o\n  JOIN customers c ON c.customer_id = o.customer_id\n  JOIN products p ON p.product_id = o.product_id\n  WHERE o.status = 'Completed'\n  GROUP BY c.customer_id, full_name\n)\nSELECT\n  full_name,\n  total_revenue,\n  RANK() OVER (ORDER BY total_revenue DESC) AS revenue_rank\nFROM customer_revenue\nORDER BY revenue_rank, full_name;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 55,
    title: "Running monthly order count",
    topic: "WINDOW FUNCTIONS",
    difficulty: "Medium",
    description: "Return order_month, order_count, and running_order_count for each month ordered by month.",
    starterSql: "WITH monthly_orders AS (\n  -- count orders per month\n)\nSELECT\n  order_month,\n  order_count,\n  -- running SUM over order_month\nFROM monthly_orders\nORDER BY order_month;",
    solutionSql: "WITH monthly_orders AS (\n  SELECT DATE_TRUNC('month', order_date)::date AS order_month, COUNT(*) AS order_count\n  FROM orders\n  GROUP BY order_month\n)\nSELECT\n  order_month,\n  order_count,\n  SUM(order_count) OVER (ORDER BY order_month) AS running_order_count\nFROM monthly_orders\nORDER BY order_month;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 56,
    title: "Most recent order per customer",
    topic: "WINDOW FUNCTIONS",
    difficulty: "Medium",
    description: "Use ROW_NUMBER to return customer_id, order_id, and order_date for each customer's most recent order.",
    starterSql: "WITH ranked_orders AS (\n  SELECT\n    customer_id,\n    order_id,\n    order_date,\n    -- row number per customer\n  FROM orders\n)\nSELECT customer_id, order_id, order_date\nFROM ranked_orders\nWHERE rn = 1;",
    solutionSql: "WITH ranked_orders AS (\n  SELECT\n    customer_id,\n    order_id,\n    order_date,\n    ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date DESC, order_id DESC) AS rn\n  FROM orders\n)\nSELECT customer_id, order_id, order_date\nFROM ranked_orders\nWHERE rn = 1;",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 57,
    title: "Insert a new customer",
    topic: "INSERT / UPDATE / DELETE",
    difficulty: "Easy",
    description: "Insert a new customer with customer_id 21. This is a manual exercise and will be rolled back.",
    starterSql: "-- Manual exercise: add one customer row.\nINSERT INTO customers (...)\nVALUES (...);",
    solutionSql: "INSERT INTO customers (customer_id, first_name, last_name, email, city, country, signup_date, segment)\nVALUES (21, 'Mert', 'Aydin', 'mert.aydin@example.com', 'Istanbul', 'Turkey', DATE '2025-02-01', 'Consumer');",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 58,
    title: "Update inactive product stock",
    topic: "INSERT / UPDATE / DELETE",
    difficulty: "Easy",
    description: "Set stock_quantity to 10 and is_active to true for the product named Legacy Webcam. This is a manual exercise and will be rolled back.",
    starterSql: "-- Manual exercise: update one product.\nUPDATE products\nSET ...\nWHERE product_name = 'Legacy Webcam';",
    solutionSql: "UPDATE products\nSET stock_quantity = 10,\n    is_active = true\nWHERE product_name = 'Legacy Webcam';",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 59,
    title: "Delete cancelled orders",
    topic: "INSERT / UPDATE / DELETE",
    difficulty: "Medium",
    description: "Delete orders whose status is Cancelled. This is a manual exercise and will be rolled back.",
    starterSql: "-- Manual exercise: delete by status.\nDELETE FROM orders\nWHERE ...;",
    solutionSql: "DELETE FROM orders\nWHERE status = 'Cancelled';",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 60,
    title: "Transfer product stock in a transaction",
    topic: "TRANSACTION",
    difficulty: "Medium",
    description: "Write a transaction that decreases product 1 stock by 2 and increases product 14 stock by 2. This is a manual exercise.",
    starterSql: "-- Manual exercise: use BEGIN and COMMIT.\nBEGIN;\n\nUPDATE products\nSET stock_quantity = stock_quantity - 2\nWHERE product_id = ...;\n\n-- second update\n\nCOMMIT;",
    solutionSql: "BEGIN;\n\nUPDATE products\nSET stock_quantity = stock_quantity - 2\nWHERE product_id = 1;\n\nUPDATE products\nSET stock_quantity = stock_quantity + 2\nWHERE product_id = 14;\n\nCOMMIT;",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 61,
    title: "Insert order and rollback",
    topic: "TRANSACTION",
    difficulty: "Medium",
    description: "Start a transaction, insert order_id 1001 for customer 1 and product 1, then roll it back. This is a manual exercise.",
    starterSql: "-- Manual exercise: prove that rollback undoes changes.\nBEGIN;\n\nINSERT INTO orders (...)\nVALUES (...);\n\nROLLBACK;",
    solutionSql: "BEGIN;\n\nINSERT INTO orders (order_id, customer_id, product_id, order_date, quantity, discount_percent, status, payment_method)\nVALUES (1001, 1, 1, DATE '2025-02-01', 1, 0, 'Completed', 'Card');\n\nROLLBACK;",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 62,
    title: "Foreign key prevents invalid orders",
    topic: "FOREIGN KEY constraint behavior",
    difficulty: "Medium",
    description: "Try inserting an order with customer_id 999. PostgreSQL should reject it because orders.customer_id references customers.customer_id. This is a manual exercise.",
    starterSql: "-- Manual exercise: this should fail because customer 999 does not exist.\nINSERT INTO orders (...)\nVALUES (...);",
    solutionSql: "INSERT INTO orders (order_id, customer_id, product_id, order_date, quantity, discount_percent, status, payment_method)\nVALUES (1002, 999, 1, DATE '2025-02-01', 1, 0, 'Completed', 'Card');",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 63,
    title: "Foreign key prevents deleting referenced customer",
    topic: "FOREIGN KEY constraint behavior",
    difficulty: "Medium",
    description: "Try deleting customer_id 1. PostgreSQL should reject it because orders reference that customer. This is a manual exercise.",
    starterSql: "-- Manual exercise: this should fail when existing orders reference the customer.\nDELETE FROM customers\nWHERE customer_id = ...;",
    solutionSql: "DELETE FROM customers\nWHERE customer_id = 1;",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 64,
    title: "Create an index on order date",
    topic: "INDEX",
    difficulty: "Medium",
    description: "Create an index named idx_orders_order_date on orders(order_date). This is a manual exercise and will be rolled back.",
    starterSql: "-- Manual exercise: create a simple index.\nCREATE INDEX ...\nON orders (...);",
    solutionSql: "CREATE INDEX idx_orders_order_date\nON orders (order_date);",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 65,
    title: "Create a composite index for customer order lookup",
    topic: "INDEX",
    difficulty: "Medium",
    description: "Create an index named idx_orders_customer_date on orders(customer_id, order_date). This is a manual exercise and will be rolled back.",
    starterSql: "-- Manual exercise: composite indexes can support multi-column filters/sorts.\nCREATE INDEX ...\nON orders (..., ...);",
    solutionSql: "CREATE INDEX idx_orders_customer_date\nON orders (customer_id, order_date);",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 66,
    title: "Explain a filtered order query",
    topic: "EXPLAIN",
    difficulty: "Medium",
    description: "Use EXPLAIN to inspect a query that filters completed orders in 2024. This is a manual exercise.",
    starterSql: "-- Manual exercise: prefix a SELECT with EXPLAIN.\nEXPLAIN\nSELECT ...\nFROM orders\nWHERE ...;",
    solutionSql: "EXPLAIN\nSELECT order_id, order_date, status\nFROM orders\nWHERE status = 'Completed'\n  AND order_date >= DATE '2024-01-01'\n  AND order_date < DATE '2025-01-01';",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 67,
    title: "Explain analyze category revenue",
    topic: "EXPLAIN",
    difficulty: "Medium",
    description: "Use EXPLAIN ANALYZE to inspect the completed revenue by category query. This is a manual exercise.",
    starterSql: "-- Manual exercise: EXPLAIN ANALYZE runs the query and shows timing.\nEXPLAIN ANALYZE\nSELECT ...;",
    solutionSql: "EXPLAIN ANALYZE\nSELECT\n  p.category,\n  ROUND(SUM(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0)), 2) AS total_revenue\nFROM orders o\nJOIN products p ON p.product_id = o.product_id\nWHERE o.status = 'Completed'\nGROUP BY p.category;",
    validationMode: "manual",
    orderMatters: false
  },
  {
    id: 68,
    title: "Executive revenue dashboard",
    topic: "final dashboard/report queries",
    difficulty: "Medium",
    description: "Return completed_orders, completed_revenue, average_order_value, and units_sold for completed orders.",
    starterSql: "-- Build one KPI row from completed orders.\nSELECT\n  COUNT(*) AS completed_orders,\n  -- completed_revenue,\n  -- average_order_value,\n  -- units_sold\nFROM orders o\nJOIN products p ON ...\nWHERE o.status = 'Completed';",
    solutionSql: "SELECT\n  COUNT(*) AS completed_orders,\n  ROUND(SUM(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0)), 2) AS completed_revenue,\n  ROUND(AVG(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0)), 2) AS average_order_value,\n  SUM(o.quantity) AS units_sold\nFROM orders o\nJOIN products p ON p.product_id = o.product_id\nWHERE o.status = 'Completed';",
    validationMode: "result_match",
    orderMatters: false
  },
  {
    id: 69,
    title: "Category performance report",
    topic: "final dashboard/report queries",
    difficulty: "Medium",
    description: "Return category, completed_orders, units_sold, and revenue for completed orders by category, ordered by revenue descending.",
    starterSql: "-- One row per category, ordered by revenue.\nSELECT\n  p.category,\n  COUNT(*) AS completed_orders,\n  -- units and revenue\nFROM orders o\nJOIN products p ON ...\nWHERE o.status = 'Completed'\nGROUP BY p.category\nORDER BY ...;",
    solutionSql: "SELECT\n  p.category,\n  COUNT(*) AS completed_orders,\n  SUM(o.quantity) AS units_sold,\n  ROUND(SUM(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0)), 2) AS revenue\nFROM orders o\nJOIN products p ON p.product_id = o.product_id\nWHERE o.status = 'Completed'\nGROUP BY p.category\nORDER BY revenue DESC;",
    validationMode: "result_match",
    orderMatters: true
  },
  {
    id: 70,
    title: "Customer leaderboard report",
    topic: "final dashboard/report queries",
    difficulty: "Medium",
    description: "Return the top 10 customers by completed revenue with full_name, completed_orders, units_sold, and revenue.",
    starterSql: "-- Join all three tables and rank customers by revenue.\nSELECT\n  c.first_name || ' ' || c.last_name AS full_name,\n  -- counts, units, revenue\nFROM orders o\nJOIN customers c ON ...\nJOIN products p ON ...\nWHERE o.status = 'Completed'\nGROUP BY c.customer_id, full_name\nORDER BY ...\nLIMIT 10;",
    solutionSql: "SELECT\n  c.first_name || ' ' || c.last_name AS full_name,\n  COUNT(*) AS completed_orders,\n  SUM(o.quantity) AS units_sold,\n  ROUND(SUM(o.quantity * p.unit_price * (1 - o.discount_percent / 100.0)), 2) AS revenue\nFROM orders o\nJOIN customers c ON c.customer_id = o.customer_id\nJOIN products p ON p.product_id = o.product_id\nWHERE o.status = 'Completed'\nGROUP BY c.customer_id, full_name\nORDER BY revenue DESC\nLIMIT 10;",
    validationMode: "result_match",
    orderMatters: true
  }
];

export function getQuestionById(id: number) {
  return questions.find((question) => question.id === id);
}
